### ISSUE TITLE
tabIndex will default to the reveal icon

### ISSUE THREAD

**Issue by OhJayDubya** [MeTaNoV/gold-password-input#8]
When using tab to navigate through fields the tabIndex will default to the reveal icon instead of going to the next field (pressing tab multiple times will just cause the focus to go back and forth between the input box and the icon button) despite setting the tabIndex = '-1' within the code (I have attempted to do this in the gold-password-input, toggle-icon and even as far down as the paper-toggle-button) however within the elements console the tabIndex still shows as '0' but if I change it through the console to '-1' it will have the desired effect and will move onto the next password input.

**Comment by GeoloeG-IsT** [comment]
@OhJayDubya I updated the element to suppress focusability to the reveal icon completely due to a restriction on PaperInputBehavior... so just update and use the element. In the future, I might reimplement the focusability of the reveal icon. If this is the case, I will add a `noIconTabbing` property to the element, so that you won't be surprised and could update directly! :)

**Comment by OhJayDubya** [comment]
Thank you very much for your help. Shall test it out tomorrow and see if everything works as expected but after looking at your demo page it looks like everything is working perfectly!
